export enum Colors {
  WHITE = '#FFFFFF',
  LIGHT_PINK = '#FFDBDB',
  PRIMARY_BLUE = '#4953BE',
  LIGHT_BLUE = '#DBDEFF',
  ORANGE = '#FFA67A',
  GINGER = '#FF7878',
  RED = '#FF6065',
  INTENSE_RED = '#CC4033',
  GREY = '#F9F9F9',
}
